name: 终极搬砖机器人

on:
  workflow_dispatch:

jobs:
  Transfer:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 静默安装 Rclone
        run: curl -s https://rclone.org/install.sh | sudo bash > /dev/null 2>&1

      - name: 2. 配置通行证
        run: |
          mkdir -p ~/.config/rclone
          rclone config create pikpak pikpak user "leyuanw560@gmail.com" pass "1796629243sky" > /dev/null 2>&1
          rclone config create 123pan webdav url "https://webdav.123pan.cn/webdav" vendor "other" user "15345447515" pass "eccuswyc" headers "User-Agent,Mozilla/5.0" > /dev/null 2>&1

      - name: 3. 开始微软云端满血搬运
        run: |
          rclone copy "pikpak:/动漫" "123pan:/PikPak中转站/动漫" --stats 60s --transfers 4 --checkers 8 --tpslimit 8 --exclude "*.torrent" --exclude "*.txt" --ignore-errors --retries 5
