name: 终极搬砖机器人

on:
  workflow_dispatch:

jobs:
  Transfer:
    runs-on: ubuntu-latest
    steps:
      - name: 1. 安装工具
        run: curl -s https://rclone.org/install.sh | sudo bash > /dev/null 2>&1

      - name: 2. 配置账号
        run: |
          mkdir -p ~/.config/rclone
          rclone config create pikpak pikpak user "leyuanw560@gmail.com" pass "1796629243sky" > /dev/null 2>&1
          rclone config create 123pan webdav url "https://webdav.123pan.cn/webdav" vendor "other" user "15345447515" pass "eccuswyc" headers "User-Agent,Mozilla/5.0" > /dev/null 2>&1

      - name: 3. 全自动无缝搬运 (加速版)
        run: |
          # 加上了 --size-only 极大加快比对速度，跳过昨晚已传的 200G
          rclone copy "pikpak:/动漫" "123pan:/PikPak中转站/动漫" --size-only --stats 60s --transfers 4 --checkers 8 --tpslimit 8 --exclude "*.torrent" --exclude "*.txt" --ignore-errors --retries 5
